// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvubqoymqdevhswixssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dWJxb3ltcWRldmhzd2l4c3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzMzODIsImV4cCI6MjA3MTcwOTM4Mn0.Ai-uLV-mSgfKH_6v0mbBiZhadIYPvBO7Twmn5DkX_3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});